#!/usr/bin/env bash
# ============================================================================
# OpenClaw Shared Library - .env File Generation
# ============================================================================

generate_env() {
    header "Generating Configuration"

    cat > "$ENV_FILE" <<EOF
# ============================================================================
# OpenClaw - Configuration
# Generated by install.sh on $(date)
# Mode: ${INSTALL_MODE}
# ============================================================================

# ---- AI Provider (Grok is the default) ----
AI_PROVIDER=${AI_PROVIDER:-grok}
OPENCLAW_PRIMARY_MODEL=${OPENCLAW_PRIMARY_MODEL:-grok-3}

# ---- API Keys ----
XAI_API_KEY=${XAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY:-}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
GROQ_API_KEY=${GROQ_API_KEY:-}
PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-}
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
COHERE_API_KEY=${COHERE_API_KEY:-}
${OLLAMA_BASE_URL:+OLLAMA_BASE_URL=${OLLAMA_BASE_URL}}

# ---- Channels ----
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
WHATSAPP_ENABLED=${WHATSAPP_ENABLED:-false}
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-}
SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
SLACK_APP_TOKEN=${SLACK_APP_TOKEN:-}

# ---- SMTP ----
SMTP_HOST=${SMTP_HOST:-}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USER=${SMTP_USER:-}
SMTP_PASSWORD=${SMTP_PASSWORD:-}
SMTP_FROM=${SMTP_FROM:-openclaw@localhost}
SMTP_TLS=${SMTP_TLS:-on}

# ---- Gateway ----
OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}
OPENCLAW_GATEWAY_BIND=${OPENCLAW_GATEWAY_BIND:-lan}

# ---- Tor ----
TOR_ENABLED=${TOR_ENABLED:-true}
TOR_SOCKS_PORT=${TOR_SOCKS_PORT:-9050}

# ---- Desktop / VNC ----
ENABLE_VNC=${ENABLE_VNC:-true}
VNC_PASSWORD=${VNC_PASSWORD:-}
DISPLAY_RESOLUTION=${DISPLAY_RESOLUTION:-1920x1080x24}

# ---- Logging ----
OPENCLAW_LOG_LEVEL=info
EOF

    chmod 600 "$ENV_FILE"
    log "Configuration saved to ${ENV_FILE}"
}
